# Generated by Django 4.2 on 2024-04-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembled_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='members',
            field=models.ManyToManyField(to='ensembled_app.musician'),
        ),
    ]
