# Generated by Django 4.2 on 2024-04-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembled_app', '0002_band_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='members',
            field=models.ManyToManyField(related_name='Bands', to='ensembled_app.musician'),
        ),
    ]
