# Generated by Django 4.2 on 2024-04-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembled_app', '0003_alter_band_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
