# Generated by Django 4.2 on 2024-04-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembled_app', '0004_band_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('Alternative', 'Alternative'), ('Blues', 'Blues'), ('Classical', 'Classical'), ('Concert Band', 'Concert Band'), ('Country', 'Country'), ('Electronic', 'Electronic'), ('Folk', 'Folk'), ('Hip Hop', 'Hip Hop'), ('Jazz', 'Jazz'), ('Latin', 'Latin'), ('Metal', 'Metal'), ('Orchestral', 'Orchestral'), ('Pop', 'Pop'), ('R&B', 'R&B'), ('Rock', 'Rock'), ('World', 'World'), ('Other', 'Other')], max_length=100),
        ),
    ]
