# Generated by Django 4.2 on 2024-04-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembled_app', '0005_alter_band_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
