# Generated by Django 4.2 on 2024-04-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembled_app', '0006_musician_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='Bands', to='ensembled_app.musician'),
        ),
    ]
