# Generated by Django 4.2 on 2024-04-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembled_app', '0007_alter_band_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('Alternative', 'Alternative'), ('Blues', 'Blues'), ('Classical', 'Classical'), ('Concert Band', 'Concert Band'), ('Country', 'Country'), ('Electronic', 'Electronic'), ('Folk', 'Folk'), ('Hip Hop', 'Hip Hop'), ('Jazz', 'Jazz'), ('Latin', 'Latin'), ('Metal', 'Metal'), ('Orchestral', 'Orchestral'), ('Pop', 'Pop'), ('R&B', 'R&B'), ('Rock', 'Rock'), ('World', 'World'), ('Other', 'Other')], max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('Alternative', 'Alternative'), ('Blues', 'Blues'), ('Classical', 'Classical'), ('Concert Band', 'Concert Band'), ('Country', 'Country'), ('Electronic', 'Electronic'), ('Folk', 'Folk'), ('Hip Hop', 'Hip Hop'), ('Jazz', 'Jazz'), ('Latin', 'Latin'), ('Metal', 'Metal'), ('Orchestral', 'Orchestral'), ('Pop', 'Pop'), ('R&B', 'R&B'), ('Rock', 'Rock'), ('World', 'World'), ('Other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='musician',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='musician',
            name='instruments',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='musician',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
