# Generated by Django 4.2 on 2024-04-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembled_app', '0008_event_alter_band_genre_alter_band_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bands',
            field=models.ManyToManyField(blank=True, related_name='Concerts', to='ensembled_app.band'),
        ),
    ]
